version: "3.3"
services:
  db:
    image: postgres:16.4
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./sql/main_ddl.sql:/docker-entrypoint-initdb.d/main_ddl.sql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", $POSTGRES_USER, "-d", $POSTGRES_DB]
      interval: 2s
      timeout: 1s
      retries: 2
      start_period: 1s

volumes:
  database_data:
    driver: local
